language: c
compiler:
 - gcc
 - clang
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq ninja libcap-dev uuid-dev libnl-route-3-dev python-pip python-dev build-essential
 - sudo pip3 install --upgrade pip
 - sudo pip3 install meson
script:
 - meson build
 - cd build
 - ninja
 - ninja install
