language: c

services:
 - docker

addons:
   apt:
      packages:
         - docker-ce

before_install:
 - docker build -t nsexec -f travis-ci/Dockerfile .

script:
 - docker run -d nsexec /bin/bash -c "cd nsexec; meson build; ninja -C build"
 - docker run -d nsexec /bin/bash -c "cd nsexec; CC=clang meson build2; ninja -C build2"
