language: c
services:
 - docker
compiler:
 - gcc
 - clang

addons:
   apt:
      packages:
         - docker-ce

before_install:
 - docker run -dti --name travis_build fedora:latest bash
 - docker exec -ti travis_build bash -c "dnf install meson ninja-build gcc clang libuuid-devel libnl3-devel libcap-devel"
script:
 - docker exec -ti travis_build meson build
 - docker exec -ti travis_build ninja -C build
